### ISSUE TITLE
Class 'Ismaelw\Latex' not found 

### ISSUE THREAD

**Issue by dhruva81** [ismaelw/laravel-php-latex#1]
Hi

I am not to dry run it  and following error is coming.

```
Error
Class 'Ismaelw\Latex' not found 
```

![image](https://user-images.githubusercontent.com/42173738/102866939-0a93b900-445e-11eb-94b6-5c3bbf59c2d7.png)

**Comment by ismaelw** [comment]
Hi!

What Laravel Version are you using to install this package?

**Comment by dhruva81** [comment]
Hi @ismaelw 
Thank you for reply

I am using  Laravel 8.12

**Comment by ismaelw** [comment]
Hi @dhruva81 

Let me get this right. Installation worked, but the dryrun doesn‘t work?

Which steps you did and what code snippets you already have?

**Comment by ismaelw** [comment]
hi @dhruva81 

Please tell me if I can assist you 👍 
I didn‘t quiet got to test the package with Windows and Laravel 8. If it works with Windows please let me know! :)

**Comment by dhruva81** [comment]
Hi @ismaelw 

Thank you for reply.

I have installed laravel 8.12 with jetsream. 

When  I am trying to install your package using composer require 
I am getting some messages like 'class does not comply with psr-4 autoloading standard. skipping.'

Also when I try to dry run using your controller method,
I am getting message  Class 'Ismaelw\Latex' does not found.

```
use \Ismaelw\Latex;

class LatexController extends Controller
{
   
 // public function download(){

    //     return (new Latex)->dryRun();
        
    // }


    public function download(){

        return (new Latex('latex.tex'))->with([
            'name' => 'John Doe',
            'dob' => '01/01/1994',
            'addresses' => [
                '20 Pumpkin Hill Drive Satellite Beach, FL 32937',
                '7408 South San Juan Ave. Beaver Falls, PA 15010'
            ]
        ])->download('test.pdf');
    }
}

```

**Comment by ismaelw** [comment]
Hi @dhruva81 
Please try by removing the leading backslash:

From:

`use \Ismaelw\Latex;`

to:

`use Ismaelw\Latex;`

**Comment by dhruva81** [comment]
Hi @ismaelw 

I have tried using 
```
use Ismaelw\Latex;
```

But still it is showing same error :(

I think the issue is 'psr-4 autoloading' but i am not able to figure out how to fix it.

**Comment by ismaelw** [comment]
Hi @dhruva81 

While testing in my environment (Composer 2.0 & Laravel 8.x) I realized that there was indeed an issue in PSR-4 Autoloading.
The problem there is the compatibility between composer 2 and psr4 where the correct Namespacing etc. is really important.

After Updating my package I am now able to install it in Laravel 8 without those warnings and the usage of the package worked for me.

To be sure please use the `--no-chache` switch to require my package again.
`composer require ismaelw/laravel-php-latex --no-cache`

Please keep me updated on your progress!

**Comment by dhruva81** [comment]
Hi @ismaelw 

Thank you for updating this awesome package.

All previous issues are resolved.
I am now able to install without any PSR-4 autoloading error message and class 'Ismaelw\Latex' not found error.

Thank you very much.

But I am facing another issue. May be it is not related to this package.

```
Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException
The file "C:\laragon\www\laratry\storage\app\temp\cT06176.tmp.pdf" does not exist 
```
![image](https://user-images.githubusercontent.com/42173738/103153251-478ce200-47b5-11eb-8748-b407ccfc652a.png)

When I check in tmp folder PDF files are generated.

![image](https://user-images.githubusercontent.com/42173738/103153266-6ab79180-47b5-11eb-9eb7-97d570fc8299.png)

I never worked earlier with files : (

My config/filesystems.php 

![image](https://user-images.githubusercontent.com/42173738/103153316-ca15a180-47b5-11eb-8b36-092c84a6e42d.png)

I have given fill permission to storage folder as well as I have also created symbolic link using 

```
php artisan storage:link
```

Kindly guide me, is there any setting or configuration needed to download pdf generated.

Thanks

**Comment by ismaelw** [comment]
Hi @dhruva81 

Thanks for your feedback. I am happy that I can help.

There is one point in your new issue that makes me think.
But first I have to say it looks like the package works almost fine.
The Files .aux and .log are files generated while converting the .tex file to a .pdf.

Now the problem I see with your pdflatex is that a .tmp file is generated. The reason for this is that I use the PHP function "tempnam(path, filename)" to generate a temporary file.

I think PHP running on Windows always adds a .tmp extension to the file generated by "tempnam"
PHP running on linux will create a file without an extension.

How this package was initially created for the usage on unix systems I will have to change a few things about the package.

--> Can you tell me if you find out, where exactly you receive your exception? Most likely it's going to be somewhere in a function inside my Latex class. 

Unfortunately I see that the Teardown function doesn't work correctly as after the pdf creation it should delete all the files (.aux, .log etc.). I am looking for a fix there right now.

**Comment by ismaelw** [comment]
Hi @dhruva81 

I am just making a guess on your problems solution and I thought about a workaround right now.

Please replace in my Latex.php the "generate" function with the following one:

```php
private function generate(){

    	$fileName = Str::random(10);
        $basetmpfname = tempnam(storage_path('app/temp/'), $fileName);
        $tmpfname = preg_replace('/\\.[^.\\s]{3,4}$/', '', $basetmpfname);
        rename($basetmpfname, $tmpfname);
        $tmpDir = storage_path('app/temp');
        chmod($tmpfname, 0755);

        \File::put($tmpfname, $this->renderedTex);

        $program    = $this->binPath ? $this->binPath : 'pdflatex';
        $cmd        = [$program, '-output-directory', $tmpDir, $tmpfname];

        $process    = new Process($cmd);
        $process->run();
        if (!$process->isSuccessful()) {
            \Event::dispatch(new LatexPdfFailed($fileName, 'download', $this->metadata));
        	$this->parseError($tmpfname, $process);
        }

        $this->teardown($tmpfname);

        register_shutdown_function(function () use ($tmpfname) {
            if(\File::exists($tmpfname . '.pdf')){
                \File::delete($tmpfname . '.pdf');
            }
        });

        return $tmpfname.'.pdf';
    }
```

And then try again. Please tell me if that works and what your result is

**Comment by dhruva81** [comment]
Hi @ismaelw 

You are genius :+1: :100: 

I have tried with your new "generate" function  of Latex.php

and it is working perfectly without any error.

Thank you very much.


Now when I am trying to save generated PDF in a folder according to your documentation, I am getting another exception. May be it is also related to windows.
```
(new Latex('latex.tex'))->with([
    'name' => 'John Doe',
    'dob' => '01/01/1994',
    'addresses' => [
        '20 Pumpkin Hill Drive Satellite Beach, FL 32937',
        '7408 South San Juan Ave. Beaver Falls, PA 15010'
    ]
])->savePdf(storage_path('exports/pdf/test.pdf'));
```

![image](https://user-images.githubusercontent.com/42173738/103154673-e964fc80-47be-11eb-9224-8ec51d7d849a.png)

**Comment by ismaelw** [comment]
Hi @dhruva81 
Thank you so much for testing.

Your next issue is indeed Windows-Related.
How in unix systems you build paths with forward-slashes in Windows you use backslashes.

Try using `->savePdf(storage_path('exports\pdf\test.pdf'));` (so I exchanged the forward slashes with backslashes)

If you are already testing could you also please test the following "teardown" function that isalso in my Latex.php file?

```php
private function teardown($tmpfname)
{
    if(\File::exists(storage_path('app/temp/' . $tmpfname))) {
        \File::delete(storage_path('app/temp/' . $tmpfname));
    }
    if(\File::exists(storage_path('app/temp/' . $tmpfname . '.aux'))) {
        \File::delete(storage_path('app/temp/' . $tmpfname . '.aux'));
    }
    if(\File::exists(storage_path('app/temp/' . $tmpfname . '.log'))) {
        \File::delete(storage_path('app/temp/' . $tmpfname . '.log'));
    }
    if(\File::exists(storage_path('app/temp/' . $tmpfname . '.out'))) {
        \File::delete(storage_path('app/temp/' . $tmpfname . '.out'));
    }

    return $this;
}
```

Just to see if all the .aux, .log, .out files get removed after saving or downloading a pdf file.

**Comment by dhruva81** [comment]
Hi @ismaelw 

(1) I have changed the forward slashes with backward slashes `->savePdf(storage_path('exports\pdf\test.pdf'))`
But it is throwing some exception :(

![image](https://user-images.githubusercontent.com/42173738/103155453-3d271400-47c6-11eb-8110-5fb84ee35445.png)

(2)  On using ` ->download('test.pdf');` after downloading PDF file, some files are not removing from tmp folder.

![image](https://user-images.githubusercontent.com/42173738/103155491-8a0aea80-47c6-11eb-8e47-0b35f18f72da.png)

**Comment by ismaelw** [comment]
Hi @dhruva81 

Thanks for your tests. Could you please check the following two things:

- Does the PDF file "C:\laragon\www\laratry\storage\app\temp\syAA8FD.pdf" exist?
- Do the Folders "exports" and "pdf" exist directly inside of your "storage" folder?

**Comment by dhruva81** [comment]
Hi @ismaelw 

The PDF file "C:\laragon\www\laratry\storage\app\temp\syAA8FD.pdf"  does not exist.
Yes, the folders "exports" and "pdf" exist directly inside of my "storage" folder.

**Comment by ismaelw** [comment]
Hi @dhruva81 

Basically what happens is that I create a temp file, put the latex content into it and render it using pdflatex with a given filename (tempname.pdf). After that I send the file back, and let it either download or save it (so move it to the new destination).

Could you comment out the teardwon function and the shutdown function inside of the "generate" function?

like this:

```php
private function generate(){

 $fileName = Str::random(10);
    $basetmpfname = tempnam(storage_path('app/temp/'), $fileName);
    $tmpfname = preg_replace('/\\.[^.\\s]{3,4}$/', '', $basetmpfname);
    rename($basetmpfname, $tmpfname);
    $tmpDir = storage_path('app/temp');
    chmod($tmpfname, 0755);

    \File::put($tmpfname, $this->renderedTex);

    $program    = $this->binPath ? $this->binPath : 'pdflatex';
    $cmd        = [$program, '-output-directory', $tmpDir, $tmpfname];

    $process    = new Process($cmd);
    $process->run();
    if (!$process->isSuccessful()) {
        \Event::dispatch(new LatexPdfFailed($fileName, 'download', $this->metadata));
     $this->parseError($tmpfname, $process);
    }

    // $this->teardown($tmpfname);
    // 
    // register_shutdown_function(function () use ($tmpfname) {
    //     if(\File::exists($tmpfname . '.pdf')){
    //         \File::delete($tmpfname . '.pdf');
    //     }
    // });

    return $tmpfname.'.pdf';
}
```

Like this after rendering the pdf nothing gets deleted. And then please see which temporary files you still have and if the PDF file is saved to your desired location.

**Comment by ismaelw** [comment]
Hi @dhruva81 

You inspired me to work on a better version of this package.
For this I invested some time to create the following package: [https://github.com/ismaelw/laratex/](https://github.com/ismaelw/laratex/)

I would appreciate if you could remove this package and install the other one. How it works is almost the same.
Also I recreated almost the whole README on the new package and implemented a Settings file.
If you need assistance installing the other one please write me!

We can also go on working on this one, and I will implement every progress here inside of my new package.
As you wish.

Oh and please update this package if you wish to continue with this oneas I published some updates also here which are fixing the teardown function.

**Comment by dhruva81** [comment]
Hi @ismaelw 

Thank you for creating new package.

Your new package is working perfectly on windows for Downloading PDFs and Exporting PDF in a folder :) 

I have also tried downloading zip and exporting in folder and a error was thrown 

```
Call to undefined function Ismaelw\LaraTeX\str_random() 
```

from function `makeCollectionDir()`  from LaratexCollection.php

So I replaced 
`$this->collectionDir = $tmpDir . DIRECTORY_SEPARATOR .'texcollection'.str_random(10);` 
 with  
`$this->collectionDir = $tmpDir . DIRECTORY_SEPARATOR .'texcollection'.Str::random(10);`

and it worked fine :)

I have not tested your new package on unix. 

Kindly let me know, will your new package also work on unix as my site will be hosted on digital ocean (Ubuntu 18.x)

Again Thank you for this wonderful package.

**Comment by ismaelw** [comment]
Hi @dhruva81 

**(1)** 
Thank you so much for your feedback and the testing. 💯 
I just updated the code for the random string function.

You are now free to update the package in your laravel test environment 👍🏼 

Am I correct that by using ismaelw/laratex you have no issues in windows anymore?

**(2)** 
I am using my new package on unix (FreeBSD) and it works perfectly. So I would say it won't be a problem for your Ubuntu machine. My hosting provider doesn't have any other options on which system I can use. I would say Digital Oceans option should be fine. Just make sure you have pdflatex installed.

On my hosting provider Iam not able to use pdflatex just like that using the shell and running "pdflatex". That's why there is the implemented feature to pass the bin path in the configuration which you can find out on unix by running "which pdflatex".

The package could maybe also work with xelatex or luatex. There I didn't had the chance to test it because my hosting provider won't install xelatex or luatex.

Keep me updated if you have any issues running the packagein your new environment on Digital Ocean. 👍🏼

**Comment by dhruva81** [comment]
Hi @ismaelw 

(1) Yes, It is working perfectly on windows machine. :)
(2) I will test this package on digital ocean server in few days. I will update you. 

IYou can close this issue as it is resolved. Thank you very much. :+1:  :100:

**Comment by ismaelw** [comment]
Hi @dhruva81 

Thank you so much! I will close this issue now.
